sudo: required

language: ruby

rvm:
  - 2.2.3

git:
  depth: 25

services:
  - docker

before_install:
  - docker build -t rmarchei/solr .
  - docker run -d -p 127.0.0.1:8983:8983 rmarchei/solr -m 1g
  - docker ps -a

script:
  - true
